name: digit_recognition
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - blas=2.121
  - blas-devel=3.9.0
  - ca-certificates=2023.12.12
  - click=8.1.7
  - flask=2.2.5
  - importlib-metadata=7.0.1
  - itsdangerous=2.0.1
  - jinja2=3.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.26
  - llvm-openmp=17.0.6
  - ncurses=6.4
  - nomkl=3.0
  - numpy-base=1.24.3
  - openblas=0.3.26
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.8.18
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - werkzeug=2.3.8
  - wheel=0.41.2
  - xz=5.4.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - filelock==3.13.1
      - fsspec==2024.2.0
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - opencv-python==4.9.0.80
      - pillow==10.2.0
      - python-mnist==0.7
      - sympy==1.12
      - torch==2.2.1
      - torchvision==0.17.1
      - typing-extensions==4.9.0
